version: '3.8'
services:
    server:
        image: nginx:alpine
        ports:
            - "${SERVER_PORT:-8080}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


    php:
        build: ./docker/php
        volumes:
            - ./:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ./.env

    database:
        image: mariadb:10
        env_file:
            - ./.env
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "${DB_PORT:-3306}:3306"

    node:
        image: node:latest
        command: npm run dev
        ports:
            - 3000:3000
        volumes:
            - .:/app
        working_dir: /app

volumes:
    db-data:
